disabled_rules:
  - variable_name
  - nesting
  - function_parameter_count
opt_in_rules:
  - control_statement
  - empty_count
  - trailing_newline
  - colon
  - comma
included:
  - SampleDeviceAndSensorInfoApp
  - SampleDeviceAndSensorInfoAppTests
excluded:
  - Pods

force_cast: error

force_try:
  severity: error

type_body_length:
  - 300 # warning
  - 400 # error

line_length:
   - 180 # warning
   - 200 # error  

file_length:
  warning: 500
  error: 800

large_tuple:
   - 3 # warning
   - 4 # error

type_name:
  min_length: 4 #warning
  max_length: # warning and error
    warning: 40
    error: 45
  excluded: iPhone # excluded via string
reporter: "xcode"